version: "3"
services:
  web:
    build: .
    command: node app.js
    volumes:
      - .:/usr/app
    ports:
      - "30010:30010"
    depends_on:
      - db      
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - HOST=0.0.0.0
    depends_on:
      - db